version: 2
jobs:
  test_back:
    docker:
      - image: maven:3.5.2-jdk-8

    working_directory: ~/ffyn

    steps:
      - checkout:
          path: ~/ffyn

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_back